apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: authentik-secrets
  namespace: iam
spec:
  organizationId: "04c22c03-d9e9-4cb7-8601-ab6c0018dacf"
  secretName: authentik-secrets
  map:
    - bwSecretId: 50898397-500f-44d8-a296-b199001d37fc 
      secretKeyName: secret-key
    - bwSecretId: 485c6b92-b4d5-428b-99c3-b199001b2316 
      secretKeyName: pg-username
    - bwSecretId: b01ee085-cec7-4c1f-8895-b199001b58ec
      secretKeyName: pg-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
