---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: proxmox-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: proxmox
addressType: IPv4
ports:
  - name: http # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - "172.16.1.110"
    conditions: {}
  - addresses:
      - "172.16.1.111"
    conditions: {}
  - addresses:
      - "172.16.1.112"
    conditions: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Proxmox Admin
    gethomepage.dev/icon: proxmox.png
    gethomepage.dev/group: Engineering
    gethomepage.dev/name: Proxmox
    gethomepage.dev/siteMonitor: https://proxmox.seibert.family
  name: proxmox
  namespace: default
spec:
  rules:
    - host: proxmox.seibert.family
      http:
        paths:
          - backend:
              service:
                name: proxmox
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - proxmiox.seibert.family
      secretName: proxmox-cert