---
apiVersion: v1
kind: Service
metadata:
  name: replicator-p-10
  namespace: default
spec:
  type: ExternalName
  externalName: 172.16.5.10
  ports:
    - port: 7125
      name: moonraker
    - port: 80
      name: default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Replicator P-10
    gethomepage.dev/icon: printer.png
    gethomepage.dev/group: Engineering
    gethomepage.dev/name: 3D Printer 10
    gethomepage.dev/siteMonitor: https://replicator-p-10.engineering.seibert.family
  name: replicator-p-10
  namespace: default
spec:
  rules:
    - host: replicator-p-10.engineering.seibert.family
      http:
        paths:
          - backend:
              service:
                name: replicator-p-10
                port:
                  name: default
            path: /webcam/
            pathType: Exact
          - backend:
              service:
                name: replicator-p-10
                port:
                  name: moonraker
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - replicator-p-10.engineering.seibert.family
      secretName: replicator-p-10-cert