---
apiVersion: v1
kind: Service
metadata:
  name: replicator-p-10
  namespace: default
spec:
  type: ExternalName
  externalName: 172.16.5.10
  ports:
    - port: 7125
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: replicator-p-10
  namespace: default
spec:
  rules:
    - host: replicator-p-10.engineering.seibert.family
      http:
        paths:
          - backend:
              service:
                name: replicator-p-10
                port:
                  number: 7125
            path: /
            pathType: Prefix
          - backend:
              service:
                name: replicator-p-10
                port:
                  number: 80
            path: /camera/
            pathType: Prefix
  tls:
    - hosts:
        - replicator-p-10.engineering.seibert.family
      secretName: replicator-p-10-cert