---
apiVersion: v1
kind: Service
metadata:
  name: replicator-p-10
  namespace: default
spec:
  type: ExternalName
  externalName: 172.16.1.20
  ports:
    - port: 5001
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: vulcan
  namespace: default
spec:
  rules:
    - host: files.seibert.family
      http:
        paths:
          - backend:
              service:
                name: vulcan
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - files.seibert.family
      secretName: vulcan-cert