prometheus:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
      hosts:
        - prometheus.seibert.family
      tls:
        - secretName: prometheus-cert
          hosts:
            - prometheus.seibert.family
    persistentVolume:
      accessModes:
        - ReadWriteMany
      storageClass: synology-iscsi-storage
  alertmanager:
    persistence:
      accessModes:
        - ReadWriteMany
      storageClass: synology-iscsi-storage
