storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: synology-iscsi-storage
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: traefik
      gethomepage.dev/description: Metrics
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Monitoring
      gethomepage.dev/icon: prometheus.png
      gethomepage.dev/name: Prometheus
    tls:
      - hosts:
        - prometheus.seibert.family
        secretName: monitoring-prometheus-cert
    hosts:
    - host: prometheus.seibert.family
      paths:
        - path: /
          pathType: Prefix
      
grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: traefik
      gethomepage.dev/description: Grafana
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Monitoring
      gethomepage.dev/icon: grafana.png
      gethomepage.dev/name: Grafana
    tls:
      - hosts:
        - grafana.seibert.family
        secretName: monitoring-grafana-cert
    hosts:
    - host: grafana.seibert.family
      paths:
        - path: /
          pathType: Prefix
