kube-prometheus-stack:
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: synology-iscsi-storage
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
  prometheus:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
        gethomepage.dev/description: Metrics
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: prometheus.png
        gethomepage.dev/name: Prometheus
      tls:
        - hosts:
          - prometheus.seibert.family
          secretName: monitoring-prometheus-cert
      hosts: 
        - prometheus.seibert.family
      paths:
        - /
      pathType: Prefix
    prometheusSpec:
      externalUrl: https://prometheus.seibert.family/
      routePrefix: /
  alertmanager:
    alertmanagerSpec:
      externalUrl: https://alertmanager.seibert.family/
      routePrefix: /
    ingress:
      ingressClassName: traefik
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
        gethomepage.dev/description: Monitoring Alerts
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: alertmanager.png
        gethomepage.dev/name: AlertManager
      tls:
        - hosts:
          - alertmanager.seibert.family
          secretName: monitoring-alertmanager-cert
      hosts: 
        - alertmanager.seibert.family
      paths:
        - /
      pathType: Prefix
  grafana:
    adminPassword: prom-operator
    persistence:
      enabled: true
    ingress:
      ingressClassName: traefik
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
        gethomepage.dev/description: Grafana
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: grafana.png
        gethomepage.dev/name: Grafana
      tls:
        - hosts:
          - grafana.seibert.family
          secretName: monitoring-grafana-cert
      hosts: 
        - grafana.seibert.family
      paths:
        - /
      pathType: Prefix
influxdb:
  global:
    fqdn: influxdb.seibert.family
  service:
    port: 8086
  persistentVolumeClaim:
    create: true
    accessMode: ReadWriteMany
    storageClassName: synology-iscsi-storage
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    labels:
      app: influxdb
    tls:
      - hosts:
        - influxdb.seibert.family
        secretName: influxdb-cert
    hosts:
    - host: influxdb.seibert.family
      paths:
        - path: /
          pathType: Prefix
  image:
    tag: 2.7
telegraf-sensors:
  env:
    - name: TZ
      value: UTC
    - name: INFLUX_TOKEN
      value: CPV6JF8lknCmH1IHaL5ybWwyfWikrx9CCATvclR8mo6x13TbZ02TlnDi8iIHLBz-sfeqhYrjr94vyMMV-4wHaA==
    - name: INFLUX_CONFIG_ID
      value: 0c62d0ece56e3000
    - name: INFLUX_BUCKET
      value: sensors
