fluidd:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: traefik
      gethomepage.dev/description: 3D Printer Management
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: 3D Printing
      gethomepage.dev/icon: fluidd.png
      gethomepage.dev/name: Fluidd
    tls:
      - hosts:
        - fluidd.seibert.family
        secretName: printing-fluidd-cert
    hosts: 
      - fluidd.seibert.family
    paths:
      - /
    pathType: Prefix
