fluidd:
  service:
    port: 80
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: traefik
      gethomepage.dev/description: 3D Printer Management
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: 3D Printing
      gethomepage.dev/icon: fluidd.png
      gethomepage.dev/name: Fluidd
    tls:
      - hosts:
        - fluidd.seibert.family
        secretName: printing-fluidd-cert
    labels:
      app: fluidd
    hosts:
    - host: fluidd.seibert.family
      paths:
        - path: /
          pathType: Prefix
spoolman:
  image:
    tag: "0.15"
  persistentVolumeClaim:
    storageClassName: synology-iscsi-storage
  service:
    port: "8000"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: traefik
      gethomepage.dev/description: Spool Manager
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: 3D Printing
      gethomepage.dev/icon: spoolman.png
      gethomepage.dev/name: SpoolMan
    tls:
      - hosts:
        - spoolman.seibert.family
        secretName: printing-spoolman-cert
    labels:
      app: spoolman
    hosts:
    - host: spoolman.seibert.family
      paths:
        - path: /
          pathType: Prefix