apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: authentik
spec:
  organizationId: "04c22c03-d9e9-4cb7-8601-ab6c0018dacf"
  secretName: authentik-secrets
  map:
    - bwSecretId: 50898397-500f-44d8-a296-b199001d37fc 
    secretKeyName: secret-key
  authToken:
    secretName: bw-auth-token
    secretKey: token
