apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: authentik-postgres
spec:
  organizationId: "a08a8157-129e-4002-bab4-b118014ca9c7"
  secretName: authentik-pg-credentials
  map:
    - bwSecretId: 485c6b92-b4d5-428b-99c3-b199001b2316 
    secretKeyName: username
    - bwSecretId: b01ee085-cec7-4c1f-8895-b199001b58ec
    secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token
