authentik:
  error_reporting:
    enabled: false
server:
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - authentik.seibert.family
postgresql:
  enabled: true
redis:
  enabled: true
