authentik:
  error_reporting:
    enabled: false
  secret_key: file:///authentik-secrets/secret-key
  postgresql:
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
server:
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - authentik.seibert.family
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-pg-credentials
    - name: authentik-secrets
      secret:
        secretName: authentik-secrets
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-secrets
      mountPaht: /authentik-secrets
      readOnly: true
worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
    - name: authentik-secrets
      secret:
        secretName: authentik-secrets
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-secrets
      mountPaht: /authentik-secrets
      readOnly: true
postgresql:
  enabled: true
redis:
  enabled: true
