zwavejs:
  istio:
    enabled: true

  global:
    fqdn: zwave.seibert.family
    
  certificate:
    create: true 
    issuerRef:
      name: letsencrypt-prod
    namespace: istio-ingress

  persistentVolumeClaim:
    create: true
    accessMode: ReadWriteMany
    storageClassName: synology-iscsi-storage

  image:
    tag: 9.6
