zwavejs:
  global:
    fqdn: zwave.seibert.family
    
  persistentVolumeClaim:
    create: true
    accessMode: ReadWriteMany
    storageClassName: synology-iscsi-storage

  ingress:
  # -- Create an Ingress object for exposing this chart
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    	- host: zwave.seibert.family
      	paths:
        	- path: /
          	pathType: ImplementationSpecific
    tls:
			- secretName: zwave-cert
			hosts:
				- zwave.seibert.family  
  image:
    tag: 9.6
