zwavejs:
  istio:
    enabled: true

  global:
    fqdn: zwave.seibert.family
    
  certificate:
    create: true 
    issuerRef:
      name: letsencrypt-prod
    namespace: istio-ingress

  persistentVolumeClaim:
    create: true
    accessmode: ReadWriteMany

  image:
    tag: 8.25
