zwavejs:
  global:
    fqdn: zwave.seibert.family
    
  persistentVolumeClaim:
    create: true
    accessMode: ReadWriteMany
    storageClassName: synology-iscsi-storage

  ingressRoute:
  # -- Create an Ingress object for exposing this chart
    enabled: true
  
  image:
    tag: 9.6
