apiVersion: v2
name: documentation
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "2.6.1"

dependencies:
- name: paperless-stack
  version: 0.1.32
  repository: https://helm.seibert.family/
  alias: paperless
