paperless:
  broker:
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      storageClass: synology-iscsi-storage
  database:
    configMap:
      postgresDb: paperless
      postgresPassword: paperless
      postgresUser: paperless
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      storageClass: synology-iscsi-storage
  global:
    broker:
      redis:
        enabled: true
        host: paperless-broker
        port: 6379
    database:
      postgres:
        enabled: true
        host: paperless-database
        name: paperless
        password: paperless
        port: 5432
        user: paperless
  webserver:
    service:
      port: 8000
    consumption:
      enabled: true
      nfs:
        enabled: true
        path: /volume2/paperless_consume
        server: 172.16.2.20
    env:
      fqdn: paperless.seibert.family
      timezone: America/New_York
    export:
      cronJob:
        enabled: true
      enabled: true
      nfs:
        enabled: true
        path: /volume2/paperless_export
        server: 172.16.2.20
    image:
      tag: 2.6.1
    ingress:
    # -- Create an Ingress object for exposing this chart
      enabled: true
      annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: traefik
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Electronic Filing Cabinet
          gethomepage.dev/group: Documentation
          gethomepage.dev/icon: paperless-ngx.png
          gethomepage.dev/name: Paperless NGX
      hosts:
        - host: 'paperless.seibert.family'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-ngx-tls
          hosts:
            - paperless.seibert.family
    persistentVolumeClaim:
      create: true
      size: 25Gi
      storageClassName: synology-iscsi-storage