paperless:
  broker:
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      storageClass: synology-iscsi-storage
  database:
    configMap:
      postgresDb: paperless
      postgresPassword: paperless
      postgresUser: paperless
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      storageClass: synology-iscsi-storage
  global:
    broker:
      redis:
        enabled: true
        host: documentation-broker
        port: 6379
    database:
      postgres:
        enabled: true
        host: documentation-database
        name: paperless
        password: paperless
        port: 5432
        user: paperless
  webserver:
    service:
      port: 8000
    consumption:
      enabled: true
      nfs:
        enabled: true
        path: /volume2/paperless_consume
        server: 172.16.2.20
    env:
      fqdn: paperless.seibert.family
      timezone: America/New_York
    export:
      cronJob:
        enabled: true
      enabled: true
      nfs:
        enabled: true
        path: /volume2/paperless_export
        server: 172.16.2.20
    ingress:
      enabled: true
      annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: traefik
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Electronic Filing Cabinet
          gethomepage.dev/group: Documentation
          gethomepage.dev/icon: paperless-ngx.png
          gethomepage.dev/name: Paperless NGX
      tls:
        - hosts:
            - paperless.seibert.family
          secretName: documentation-webserver-secret-key
      hosts:
      - host: paperless.seibert.family
        paths:
          - path: /
            pathType: Prefix
    secret:
      create: false
    persistentVolumeClaim:
      create: true
      size: 25Gi
      storageClassName: synology-iscsi-storage